### ISSUE TITLE
Refresh Chart data?

### ISSUE THREAD

**Issue by ciarans** [miaolz123/vue-chart#9]
Is there away to refresh a bar chart once new data has been fetched?

**Comment by atomantic** [comment]
I hacked this in manually by setting the vue data to a cloned (new) object:

pretty hacky:
```
vueData.charts.rpm = _.extend({}, vueData.charts.rpm)
```

**Comment by rockymontana** [comment]
If you set the values from the success method, the reactivity should trigger an update to the charts as well.

Otherwise you can use an event to trigger the chart to refresh (http://www.chartjs.org/docs/#scales-update-default-scale-config).

**Comment by rockymontana** [comment]
Closing
